package com.iver99.vo;

// Generated 2014-10-13 22:55:16 by Hibernate Tools 3.4.0.CR1

/**
 * LicensePlateInfo generated by hbm2java
 */
public class LicensePlateInfo implements java.io.Serializable {

	private Integer id;
	private String picture;

	public LicensePlateInfo() {
	}

	public LicensePlateInfo(String picture) {
		this.picture = picture;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

}
