package com.iver99.vo;

// Generated 2014-10-13 22:55:16 by Hibernate Tools 3.4.0.CR1

/**
 * PersonInfo generated by hbm2java
 */
public class PersonInfo implements java.io.Serializable {

	private Integer id;
	private int userId;
	private String name;
	private Short age;
	private String address;
	private String telephone;
	private String lisencePlateNum;
	private int lisenceId;

	public PersonInfo() {
	}

	public PersonInfo(int userId, int lisenceId) {
		this.userId = userId;
		this.lisenceId = lisenceId;
	}

	public PersonInfo(int userId, String name, Short age, String address,
			String telephone, String lisencePlateNum, int lisenceId) {
		this.userId = userId;
		this.name = name;
		this.age = age;
		this.address = address;
		this.telephone = telephone;
		this.lisencePlateNum = lisencePlateNum;
		this.lisenceId = lisenceId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Short getAge() {
		return this.age;
	}

	public void setAge(Short age) {
		this.age = age;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getLisencePlateNum() {
		return this.lisencePlateNum;
	}

	public void setLisencePlateNum(String lisencePlateNum) {
		this.lisencePlateNum = lisencePlateNum;
	}

	public int getLisenceId() {
		return this.lisenceId;
	}

	public void setLisenceId(int lisenceId) {
		this.lisenceId = lisenceId;
	}

}
